### ISSUE TITLE
Reviewer Authentication

### ISSUE THREAD

**Issue by VoyTechnology** [SaferPlace/saferplace#11]
> **note**
> This issue is carried over from https://github.com/SaferPlace/review/issues/8

## Description

As a crowd sourced platform, Realtime SaferPlace is bound to experience some level of accidental reports, spam, misinformation, biased and intolerant reports, as such, a review platform allows to review each report.

Since there might be reports which potentially contain sensitive information, the review portal should be locked down and only accessible by trusted individuals.

Each report action such as approving, sending alerts and commenting should contain an audit trail.

## Tasks

- [x] https://github.com/SaferPlace/infrastructure/issues/5
- [ ] #125
- [ ] https://github.com/SaferPlace/realtime/issues/12
- [ ] https://github.com/SaferPlace/realtime/issues/13
- [ ] #27

**Comment by VoyTechnology** [comment]
I have no idea (yet) how to do it properly, so rather than block open sourcing I will put it on the backlog and hope that I will have a chance to revisit it soon.
