### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by VoyTechnology** [SaferPlace/saferplace#164]
## Description

We currently have a very limited Unit tests, which do not cover much in the backend, and not at all in the frontend.

## Tasks

- [ ] RPC Unit Tests
- [ ] Database Unit Tests
- [ ] Storage Unit Tests
- [ ] Notifier Unit Tests
- [ ] Queue Unit Tests
